services:
  api:
    container_name: revolusi_api
    image: revolusi/api:local
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - revolusi_instances:/evolution/instances
    networks:
      - revolusi-net
    env_file:
      - .env
    expose:
      - 8080

volumes:
  evolution_instances:


networks:
  revolusi-net:
    name: revolusi-net
    driver: bridge
